/*
 * Copyright (C) 2017 Cirrus Logic, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *	http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Translation of CLSIC errors into strings. */

struct vega_response_codes_struct {
	char name[64];
	int code;
};

struct vega_response_codes_struct vega_response_codes[] = {
	{"CLSIC_ERR_NONE", CLSIC_ERR_NONE},
	{"CLSIC_ERR_NO_MEM", CLSIC_ERR_NO_MEM},
	{"CLSIC_ERR_INVAL_SI", CLSIC_ERR_INVAL_SI},
	{"CLSIC_ERR_INVAL_MSGID", CLSIC_ERR_INVAL_MSGID},
	{"CLSIC_ERR_INVAL_CRAN", CLSIC_ERR_INVAL_CRAN},
	{"CLSIC_ERR_INVAL_BULK", CLSIC_ERR_INVAL_BULK},
	{"CLSIC_ERR_CANCELLED", CLSIC_ERR_CANCELLED},
	{"CLSIC_ERR_INVAL_ARG", CLSIC_ERR_INVAL_ARG},
	{"CLSIC_ERR_INVAL_ADDR", CLSIC_ERR_INVAL_ADDR},
	{"CLSIC_ERR_ACCESS", CLSIC_ERR_ACCESS},
	{"CLSIC_ERR_HW", CLSIC_ERR_HW},
	{"CLSIC_ERR_FLASH", CLSIC_ERR_FLASH},
	{"CLSIC_ERR_TOO_SMALL", CLSIC_ERR_TOO_SMALL},
	{"CLSIC_ERR_WAKELOCK_HELD", CLSIC_ERR_WAKELOCK_HELD},
	{"CLSIC_ERR_INVAL_MODE", CLSIC_ERR_INVAL_MODE},
	{"CLSIC_ERR_INVAL_MODE_TRANSITION",
					       CLSIC_ERR_INVAL_MODE_TRANSITION},
	{"CLSIC_ERR_INVAL_CMD_FOR_MODE", CLSIC_ERR_INVAL_CMD_FOR_MODE},
	{"CLSIC_ERR_INVAL_USERID", CLSIC_ERR_INVAL_USERID},
	{"CLSIC_ERR_INVAL_PHRASEID", CLSIC_ERR_INVAL_PHRASEID},
	{"CLSIC_ERR_INVAL_APP_ID", CLSIC_ERR_INVAL_APP_ID},
	{"CLSIC_ERR_USER_NOT_INSTALLED", CLSIC_ERR_USER_NOT_INSTALLED},
	{"CLSIC_ERR_USER_ALREADY_INSTALLED", CLSIC_ERR_USER_ALREADY_INSTALLED},
	{"CLSIC_ERR_PHRASE_NOT_INSTALLED", CLSIC_ERR_PHRASE_NOT_INSTALLED},
	{"CLSIC_ERR_VOICEID", CLSIC_ERR_VOICEID},
	{"CLSIC_ERR_INPUT_PATH", CLSIC_ERR_INPUT_PATH},
	{"CLSIC_ERR_SECURITY_FAIL", CLSIC_ERR_SECURITY_FAIL},
	{"CLSIC_ERR_AUTH_ABORT_BARGE_IN", CLSIC_ERR_AUTH_ABORT_BARGE_IN},
	{"CLSIC_ERR_AUTH_NOT_STARTED_BARGE_IN",
					   CLSIC_ERR_AUTH_NOT_STARTED_BARGE_IN},
	{"CLSIC_ERR_INVAL_SECURITY_LVL", CLSIC_ERR_INVAL_SECURITY_LVL},
	{"CLSIC_ERR_NO_USER_IDENTIFIED", CLSIC_ERR_NO_USER_IDENTIFIED},
	{"CLSIC_ERR_NOT_INSTALLING_USER", CLSIC_ERR_NOT_INSTALLING_USER},
	{"CLSIC_ERR_ALREADY_INSTALLING_USER",
					     CLSIC_ERR_ALREADY_INSTALLING_USER},
	{"CLSIC_ERR_INVAL_REP_COUNT", CLSIC_ERR_INVAL_REP_COUNT},
	{"CLSIC_ERR_ONGOING_REP", CLSIC_ERR_ONGOING_REP},
	{"CLSIC_ERR_REPS_COMPLETE", CLSIC_ERR_REPS_COMPLETE},
	{"CLSIC_ERR_REP_TRGR_TIMEOUT", CLSIC_ERR_REP_TRGR_TIMEOUT},
	{"CLSIC_ERR_REP_UNEXPECTED_TRGR", CLSIC_ERR_REP_UNEXPECTED_TRGR},
	{"CLSIC_ERR_REP_TOO_NOISY", CLSIC_ERR_REP_TOO_NOISY},
	{"CLSIC_ERR_REP_NOT_ENOUGH_SPEECH", CLSIC_ERR_REP_NOT_ENOUGH_SPEECH},
	{"CLSIC_ERR_REP_NO_SPEECH", CLSIC_ERR_REP_NO_SPEECH},
	{"CLSIC_ERR_REP_SAT_TOO_HIGH", CLSIC_ERR_REP_SAT_TOO_HIGH},
	{"CLSIC_ERR_REP_FEATURE_OVERFLOW", CLSIC_ERR_REP_FEATURE_OVERFLOW},
	{"CLSIC_ERR_REPS_NOT_ENOUGH_VALID", CLSIC_ERR_REPS_NOT_ENOUGH_VALID},
	{"CLSIC_ERR_AUTH_IN_PROGRESS", CLSIC_ERR_AUTH_IN_PROGRESS},
	{"CLSIC_ERR_INVAL_TRGR_DOMAIN", CLSIC_ERR_INVAL_TRGR_DOMAIN},
	{"CLSIC_ERR_INVAL_ASR_BLOCK_SZ", CLSIC_ERR_INVAL_ASR_BLOCK_SZ},
	{"CLSIC_ERR_ALREADY_LISTENING", CLSIC_ERR_ALREADY_LISTENING},
	{"CLSIC_ERR_INVAL_CMD_FOR_TRGR_DOMAIN",
					   CLSIC_ERR_INVAL_CMD_FOR_TRGR_DOMAIN},
	{"CLSIC_ERR_LISTEN_NOT_STARTED", CLSIC_ERR_LISTEN_NOT_STARTED},
	{"CLSIC_ERR_INVAL_TRGR_INFO", CLSIC_ERR_INVAL_TRGR_INFO},
	{"CLSIC_ERR_INVAL_TRGR_ENGINEID", CLSIC_ERR_INVAL_TRGR_ENGINEID},
	{"CLSIC_ERR_INVAL_TRGR_PHRASEID", CLSIC_ERR_INVAL_TRGR_PHRASEID},
	{"CLSIC_ERR_ASR_PREV_REQUEST_PENDING",
					    CLSIC_ERR_ASR_PREV_REQUEST_PENDING},
	{"CLSIC_ERR_ASR_STREAM", CLSIC_ERR_ASR_STREAM},
	{"CLSIC_ERR_ASR_STREAM_DISABLED", CLSIC_ERR_ASR_STREAM_DISABLED},
	{"CLSIC_ERR_KEY_NOT_FOUND", CLSIC_ERR_KEY_NOT_FOUND},
	{"CLSIC_ERR_BPB_SZ_TOO_SMALL", CLSIC_ERR_BPB_SZ_TOO_SMALL},
	{"CLSIC_ERR_BPB_SZ_UNALIGNED", CLSIC_ERR_BPB_SZ_UNALIGNED},
	{"CLSIC_ERR_BPB_BAD_HDR", CLSIC_ERR_BPB_BAD_HDR},
	{"CLSIC_ERR_BPB_BAD_IMGMAP", CLSIC_ERR_BPB_BAD_IMGMAP},
	{"CLSIC_ERR_BPB_SZ_INCONSISTENT", CLSIC_ERR_BPB_SZ_INCONSISTENT},
	{"CLSIC_ERR_BPB_AUTH_FAILED", CLSIC_ERR_BPB_AUTH_FAILED},
	{"CLSIC_ERR_COV_DISABLED", CLSIC_ERR_COV_DISABLED},
	{"CLSIC_ERR_INVALID_ENROL_DURATION", CLSIC_ERR_INVALID_ENROL_DURATION},
	{"CLSIC_ERR_INVALID_AUTH_RESULT_FORMAT",
					  CLSIC_ERR_INVALID_AUTH_RESULT_FORMAT},
	{"CLSIC_ERR_BPB_ASSET_INVAL_VER", CLSIC_ERR_BPB_ASSET_INVAL_VER},
	{"CLSIC_ERR_BPB_ASSET_INVAL_SZ", CLSIC_ERR_BPB_ASSET_INVAL_SZ},
	{"CLSIC_ERR_BPB_ASSET_INVAL_COMP_TYPE",
					   CLSIC_ERR_BPB_ASSET_INVAL_COMP_TYPE},
	{"CLSIC_ERR_BPB_ASSET_INVAL_COMP_TABLE_SZ",
				       CLSIC_ERR_BPB_ASSET_INVAL_COMP_TABLE_SZ},
	{"CLSIC_ERR_BPB_ASSET_INVAL_FLAGS", CLSIC_ERR_BPB_ASSET_INVAL_FLAGS},
	{"CLSIC_ERR_BL_AUTH_FAILED", CLSIC_ERR_BL_AUTH_FAILED},
	{"CLSIC_ERR_BL_INVAL_VERSION", CLSIC_ERR_BL_INVAL_VERSION},
	{"CLSIC_ERR_BL_FLASH_WRITE_FAILED", CLSIC_ERR_BL_FLASH_WRITE_FAILED},
	{"CLSIC_ERR_BL_ARB_CHECK_FAILED", CLSIC_ERR_BL_ARB_CHECK_FAILED},
	{"CLSIC_ERR_BL_CLUB_TOO_LARGE", CLSIC_ERR_BL_CLUB_TOO_LARGE},
	{"CLSIC_ERR_BL_IMG_NAME_CLASH", CLSIC_ERR_BL_IMG_NAME_CLASH},
	{"CLSIC_ERR_BL_CAB_NOT_1ST_IN_MAB", CLSIC_ERR_BL_CAB_NOT_1ST_IN_MAB},
	{"CLSIC_ERR_BL_TOO_MANY_IMGS", CLSIC_ERR_BL_TOO_MANY_IMGS},
	{"CLSIC_ERR_BL_NO_MIN_SET_IN_MAB", CLSIC_ERR_BL_NO_MIN_SET_IN_MAB},
	{"CLSIC_ERR_BL_FLASH_ERASE_FAILED", CLSIC_ERR_BL_FLASH_ERASE_FAILED},
	{"CLSIC_ERR_BL_FLASH_READ_FAILED", CLSIC_ERR_BL_FLASH_READ_FAILED},
	{"CLSIC_ERR_BL_NBS2_NOT_1ST_IN_CAB", CLSIC_ERR_BL_NBS2_NOT_1ST_IN_CAB},
	{"CLSIC_ERR_BL_OSAPP_NOT_2ND_IN_CAB",
					     CLSIC_ERR_BL_OSAPP_NOT_2ND_IN_CAB},
};
