#
# Makefile for the CLUBB device family
#
obj-$(CONFIG_USB_CLUBB)		+= core-clubb.o
obj-$(CONFIG_GPIO_CLUBB)	+= gpio-clubb.o 
obj-$(CONFIG_I2C_CLUBB)		+= i2c-clubb.o
obj-$(CONFIG_I2S_CLUBB)		+= i2s-clubb.o
